[package]
name = "lpc55"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

[[bin]]
name = "lpc55"
required-features = ["cli"]

[dependencies]
ansi_term = "0.12.1"
bitflags = "1.2.1"
clap = { version = "2.33.3", default-features = false, optional = true }
enum-iterator = "0.6.0"
hidapi = "1.2.3"
serde = "1.0.117"
log = "0.4.11"
lazy_static = "1.4.0"

[dev-dependencies]
insta = "1.1.0"

[build-dependencies]
clap = { version = "2.33.3", default-features = false }
lazy_static = "1.4.0"

[features]
default = ["cli"]
cli = ["clap"]
