[package]
name = "lpc55"
version = "0.1.0-pre"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
exclude = ["archlinux"]

[[bin]]
name = "lpc55"
required-features = ["cli"]

[dependencies]
ansi_term = "0.12.1"
anyhow = "1"
bitflags = "1.2.1"
clap = { version = "2.33.3", default-features = false, optional = true }
enum-iterator = "0.6.0"
hidapi = { version = "1.2.3", default-features = false, features = ["linux-static-hidraw"] }
nom = { version = "6" }
serde = "1.0.117"
serde-big-array = "0.3.0"
serde_json = "1"
serde_yaml = "0.8.14"
log = "0.4.11"
lazy_static = "1.4.0"
tiny_http = { version = "0.7", optional = true }
toml = "0.5.7"

[dev-dependencies]
insta = "1.1.0"

[build-dependencies]
clap = { version = "2.33.3", default-features = false }
lazy_static = "1.4.0"

[features]
default = ["cli"]
cli = ["clap", "http"]
http = ["tiny_http"]
