root_cert_filenames = [
	"example-root-certs/ca_certificate_0.der",
	"example-root-certs/ca_certificate_1.der",
	"example-root-certs/ca_certificate_2.der",
	"example-root-certs/ca_certificate_3.der",
]

[field]
rot_keys_status = ["Enabled", "Enabled", "Enabled", "Enabled"]
version = 3
secure_firmware_version = 1
nonsecure_firmware_version = 1

[field.boot_configuration]
speed = "48Mhz"
mode = "Usb"

[factory.usb_id]
vid = 0x1209
pid = 0xb000

[factory.secure_boot_configuration]
secure_boot_enabled = true
dice_computation_disabled = true
[[factory.prince_subregions]]
bits = 0
[[factory.prince_subregions]]
bits = 0
[[factory.prince_subregions]]
bits = 0xffff

[keystore]
puf_discharge_time_milliseconds = 50
