# [bins]
# raw = "../lpc55-secure-config/example-app.bin"
# signed = "./hopefully-example-bin-signed.bin"
# secure_boot = "./example-app.sb2"
image = "blinky-red-bee.bin"
signed_image = "blinky-red-signed.bin"
secure_boot_image = "blinky-red.sb2"

build = 1
component = "0.0.0"
product = "0.0.0"

# set these for determinism (we pick all-zeroes by default, whereas elftosb picks random keys)
# dek = "32 23 18 42 94 FF A4 FC 1B F9 BA 57 6F 5F 16 38 02 F7 34 6F 1D CC 8B 21 ED 82 20 4F 92 CF 1B 1F"
# mac = "52 13 08 79 CD AC CC BF DF 61 34 F5 93 F7 B5 1B C1 D3 F4 A4 40 B3 50 F8 0E D6 D6 33 17 9B 40 B9"
# nonce = [252099056, 4098670949, 1640907152, 2101758901]
# timestamp = 664654025000000
# random_junk = "98ADCB55"
dek = "5762307D11981295FC89E8E6947087C0A3E350660D57A03AAA000C8BE5823231"
mac = "4A88F1B5B9F6A07716C4A89CC6851D519D999FDAA9EF4FF05545700F24EC1D71"
nonce = [3822587620, 613396447, 833979729, 763188229]
timestamp = 664665542000000
random_junk = "36BB2DC5"

# [pki]
root_cert_secret_key = "file:example-root-certs/ca_private_key_0.pem"
root_cert_slot = 0
# root_cert_secret_key = "pkcs11:serial=DECC0401648;object=lpc55-host-dev-ca-0;type=private?module-path=/usr/lib/onepin-opensc-pkcs11.so&pin-value=123456"
# root_cert_secret_key = "pkcs11:object=lpc55-host-dev-ca-0;type=private?module-path=/usr/lib/opensc-pkcs11.so&pin-value=123456"

# D826E2FD 44F5C254 BC58C62E BF96A938 95C19DC2 25810C95 C8B9E6FD 9F7CC9CB
root_cert_filenames = [
    "example-root-certs/ca_certificate_0.der",
    "example-root-certs/ca_certificate_1.der",
    "example-root-certs/ca_certificate_2.der",
    "example-root-certs/ca_certificate_3.der",
]

# 6A528D30 4FD8F9B7 D06FF7C4 32DFD512 09668660 6E48193B 2EB21102 0B7FD7C0
# root_cert_filenames = [
#     "lpc55-host-dev-ca-0.der",
#     "lpc55-host-dev-ca-1.der",
#     "lpc55-host-dev-ca-2.der",
#     "lpc55-host-dev-ca-3.der",
# ]

[factory.usb_id]
vid = 0x1209
pid = 0xb000

[factory.secure_boot_configuration]
# secure_boot_enabled = false
dice_computation_disabled = true

[infield]
rot_keys_status = ["Enabled", "Enabled", "Enabled", "Enabled"]
infield_version = 1
secure_firmware_version = 1
nonsecure_firmware_version = 1

[keystore]
sbkek = "AAAAAAAA AAAAAAAAA AAAAAAAA AAAAAAAA AAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"

[[commands]]
cmd = "Erase"
start = 0x0
end = 0xC00  # = 3072 = 6*512, size of blinky-red.bin is 856 bytes, signed version is 2148 bytes
# end = 512

[[commands]]
cmd = "Load"
file = "blinky-red-signed.bin"
