# [bins]
# raw = "../lpc55-secure-config/example-app.bin"
# signed = "./hopefully-example-bin-signed.bin"
# secure_boot = "./example-app.sb2"
image = "../lpc55-secure-config/example-app.bin"
signed_image = "./hopefully-example-bin-signed.bin"
secure_boot_image = "./example-app.sb2"

build = 0
component = "0.0.0"
product = "0.0.0"

# [pki]
root_cert_secret_key = "file:example-root-certs/ca_private_key_0.pem"
# root_cert_secret_key = "pkcs11:token=solo-ca;object=signing-key;type=private?module-path=/usr/lib/libsofthsm2.so&pin-source=file:pin.txt"

root_cert_filenames = [
	"example-root-certs/ca_certificate_0.der",
	"example-root-certs/ca_certificate_1.der",
	"example-root-certs/ca_certificate_2.der",
	"example-root-certs/ca_certificate_3.der",
]

[factory.usb_id]
vid = 0x1209
pid = 0xb000

[factory.secure_boot_configuration]
secure_boot_enabled = true
dice_computation_disabled = true
[[factory.prince_subregions]]
bits = 0
[[factory.prince_subregions]]
bits = 0
[[factory.prince_subregions]]
bits = 0xffff

[customer]
rot_keys_status = ["Enabled", "Enabled", "Enabled", "Enabled"]
version = 3
secure_firmware_version = 1
nonsecure_firmware_version = 1

[customer.boot_configuration]
speed = "48Mhz"
mode = "Usb"

[keystore]
puf_discharge_time_milliseconds = 50
sbkek = "0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA"

[[commands]]
cmd = "Erase"
start = 0x0
end = 0x8_9800

[[commands]]
cmd = "Load"
# file = "example-app.sb2"
file = "./hopefully-example-bin-signed.bin"
src = 512
dst = 512

[[commands]]
cmd = "Load"
# file = "example-app.sb2"
file = "./hopefully-example-bin-signed.bin"
len = 512

